[workspace]
members = [
    "circuits/transfer",
    "circuits/lock",
    "circuits/withdraw",
    "circuits/process_pending_deposits",
    "circuits/process_pending_transfers",
    "circuits/libs/bjj",
    "circuits/libs/biguint",
]
default-member = "circuits/libs/bjj"
