account_address = ""
amountSum = ""

[balance_new_to_encrypted_1]
x = ""
y = ""

[balance_new_to_encrypted_2]
x = ""
y = ""

[balance_old_to_encrypted_1]
x = ""
y = ""

[balance_old_to_encrypted_2]
x = ""
y = ""

[public_key_to]
x = ""
y = ""
